### ISSUE TITLE
contact method  is not supported

### ISSUE THREAD

**Issue by zenny** [myfreeweb/freshcerts#7]
On Ubuntu 16.04, 'bundle exec ./register-account-key' fails with "Error creating new registration :: contact method  is not supported (Acme::Client::Error::Malformed)" as of below:

```
$ bundle exec ./register-account-key                                                          
Contact (e.g. mailto:your@email.address): support@example.com
/home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': Error creating new registration :: contact method  is not supported (Acme::Client::Error::Malformed)
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `block in call'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `call'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
        from /home/acme/freshcerts/vendor/bundle/ruby/2.3.0/gems/acme-client-0.5.1/lib/acme/client.rb:45:in `register'
        from ./register-account-key:6:in `<main>'
```

**Comment by myfreeweb** [comment]
You're not entering it in the right format.

>Contact (e.g. mailto:your@email.address): support@example.com

> **m a i l t o :** your@email.address

> support@example.com
